// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjry_qqw3N2eKOpmbroMtsj5I2iU5g8a4',
    appId: '1:468446089858:web:0815544662d18b12201a9b',
    messagingSenderId: '468446089858',
    projectId: 'guess-me-bfd58',
    authDomain: 'guess-me-bfd58.firebaseapp.com',
    databaseURL: 'https://guess-me-bfd58-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'guess-me-bfd58.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmA0d3DkuGzqvKYSQURPLraTLx8LA0Hek',
    appId: '1:468446089858:android:15d3a509f253da79201a9b',
    messagingSenderId: '468446089858',
    projectId: 'guess-me-bfd58',
    databaseURL: 'https://guess-me-bfd58-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'guess-me-bfd58.firebasestorage.app',
  );
}
